include:
  - project: 'personal/infrastructure_lives'
    file: '/pipeline/backend.yml'
    ref: main

variables:
  SERVICE_NAME: "hotela"
  SERVICE_GROUP: "personal"
  PROJECT_NAME: "HOTELA_KT"
  APP_DEPLOY_MANIFEST_PATH: "k8s/deployment.yml"
  MIGRATION_DEPLOY_MANIFEST_PATH: "k8s/migration.yml"
  BUILD_CACHE_PATH: "/cache/.gradle"

cache:
  paths:
    - /cache/.gradle/wrapper/
    - /cache/.gradle/caches/

stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  image: gradle:8-jdk21
  script:
    - ./gradlew -g $BUILD_CACHE_PATH --build-cache build jacocoTestReport
  artifacts:
    paths:
      - build
  cache:
    paths:
      - $BUILD_CACHE_PATH
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_MERGE_REQUEST_ID'
      when: always
    - when: never
      allow_failure: false