apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: hotela
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotela
  namespace: hotela
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hotela
  template:
    metadata:
      labels:
        app: hotela
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'app-role'
        vault.hashicorp.com/agent-inject-secret-hotela-envs: "kv/data/app/hotela"
        vault.hashicorp.com/agent-inject-template-hotela-envs: |
          {{- with secret "kv/data/app/hotela" -}}
            {{- range $key, $value := .Data.data -}}
            export {{ $key }}="{{ $value }}"
            {{ end -}}
          {{- end }}
    spec:
      serviceAccountName: app-service-account
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: hotela
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["/bin/bash", "-c"]
          args:
            - |
                echo "Starting Hotela application with environment variables from Vault";
                source /vault/secrets/hotela-envs;
                java -jar /app/app.jar;
---
apiVersion: v1
kind: Service
metadata:
  name: hotela-service
  namespace: hotela
spec:
  type: NodePort
  selector:
    app: hotela
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
