apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: hotela
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotela
  namespace: hotela
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hotela
  template:
    metadata:
      labels:
        app: hotela
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'app-role'
        vault.hashicorp.com/agent-inject-secret-hotela-envs: kv/data/app/hotela
        vault.hashicorp.com/agent-inject-template-hotela-envs: |
          {{ with secret "kv/data/app/hotela" }}
          {{ range $key, $val := .Data.data }}
            export {{ $key }}="{{ $val }}"
          {{ end }}
          {{ end }}
    spec:
      serviceAccountName: vault-auth
      volumes:
        - name: vault-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: vault
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: hotela
          image: hotela:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service.hotela.svc.cluster.local"
          command: ["/bin/bash", "-c"]
          args:
            - |
                echo "Starting Hotela application with environment variables from Vault";
                source /vault/secrets/hotela-envs;
                java -jar /app/app.jar;
---
apiVersion: v1
kind: Service
metadata:
  name: hotela-service
  namespace: hotela
spec:
  type: NodePort
  selector:
    app: hotela
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
