apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: hotela
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hotela-db-migration
  namespace: hotela
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/exit-on-complete: 'true'
        vault.hashicorp.com/agent-inject-init-first: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/role: 'app-hotela'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/app-hotela'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{ with secret "database/creds/app-hotela" }}
            export DB_USERNAME="{{ .Data.username }}"
            export DB_PASSWORD="{{ .Data.password }}"
          {{ end }}
      labels:
        app: hotela-db-migration
    spec:
      serviceAccountName: vault-auth
      restartPolicy: OnFailure
      volumes:
        - name: vault-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: vault
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: liquibase
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "postgres-service.database.svc.cluster.local"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for Vault secrets..."

              retries=0
              max_retries=30
              
              while [ ! -f /vault/secrets/db-creds ]; do
                if [ $retries -ge $max_retries ]; then
                  echo "ERROR: Timed out waiting for Vault secrets"
                  exit 1
                fi
                retries=$((retries + 1))
                echo "Waiting... attempt ${retries}/${max_retries}"
                sleep 2
              done

              echo "Secrets received. Starting migration..."

              set -a
              source /vault/secrets/db-creds
              set +a
              
              liquibase \
                --url=jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/services \
                --username=$DB_USERNAME \
                --password=$DB_PASSWORD \
                --liquibase-schema-name=hotela \
                --default-schema-name=hotela \
                --changeLogFile=db/changelog/db.changelog-master.yaml \
                ${LIQUIBASE_COMMAND}
