apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotela
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'app-role'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'kv/data/app/hotela'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "kv/data/app/hotela" -}}
          export POSTGRES_USER="{{ .Data.data.DB_USER }}"
          export POSTGRES_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          {{- end }}
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vault-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: hotela
            - name: TZ
              value: UTC
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: hotela
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432