CREATE SCHEMA IF NOT EXISTS hotela;

GRANT USAGE, CREATE ON SCHEMA hotela TO hotela_admins;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hotela TO hotela_admins;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hotela TO hotela_admins;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA hotela TO hotela_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON TABLES TO hotela_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON SEQUENCES TO hotela_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON FUNCTIONS TO hotela_admins;
