GRANT USAGE, CREATE ON SCHEMA hotela TO current_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hotela TO current_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hotela TO current_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA hotela TO current_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON TABLES TO current_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON SEQUENCES TO current_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA hotela
GRANT ALL ON FUNCTIONS TO current_user;
