--liquibase formatted sql

--changeset lucas.araujo:001-create-types
CREATE TYPE PARTNER_STATUS AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE ROOM_STATUS AS ENUM ('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'UNAVAILABLE');
CREATE TYPE PAYMENT_METHOD AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'PIX', 'BANK_TRANSFER', 'PAYPAL', 'CASH', 'VOUCHER');
CREATE TYPE PAYMENT_STATUS AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUND', 'PARTIALLY_REFUNDED', 'CANCELLED');
CREATE TYPE BOOKING_STATUS AS ENUM ('PENDING_CONFIRMATION', 'CONFIRMED', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_HOTEL', 'CHECKED_IN', 'CHECKED_OUT', 'NO_SHOW');
CREATE TYPE USER_ROLE AS ENUM ('CUSTOMER', 'PARTNER')

--rollback DROP TYPE IF EXISTS BOOKING_STATUS;
--rollback DROP TYPE IF EXISTS PAYMENT_STATUS;
--rollback DROP TYPE IF EXISTS PAYMENT_METHOD;
--rollback DROP TYPE IF EXISTS ROOM_STATUS;
--rollback DROP TYPE IF EXISTS PARTNER_STATUS;
--rollback DROP TYPE IF EXISTS USER_ROLE;